app/blueprints/admin_panel/views.py
from app import forms, db, app
from app.models import User, Object, Category, Island
from flask import (
        Blueprint, render_template, redirect, flash, request, url_for
)
from flask_login import login_user, logout_user, login_required, current_user
import bcrypt
import time
import hashlib
import os
import datetime


admin_panel = Blueprint('admin_panel', __name__,
                        template_folder='templates',
                        url_prefix='/admin')


@admin_panel.route('/')
@login_required
def admin():
    add_object_form = forms.Object()
    mod_object_form = forms.Modify_Object()
    add_cat_form = forms.Category()
    mod_cat_form = forms.Modify_Category()
    mod_isl_form = forms.Modify_Island()

    add_user_form = forms.Add_User()
    mod_user_form = forms.Modify_User()
    return render_template('admin.html',
                           add_object_form=add_object_form,
                           mod_object_form=mod_object_form,
                           add_cat_form=add_cat_form,
                           mod_cat_form=mod_cat_form,
                           mod_isl_form=mod_isl_form,
                           add_user_form=add_user_form,
                           mod_user_form=mod_user_form,

                           user=current_user
                           )


''' Object handlers '''


@admin_panel.route('/add_object', methods=['GET', 'POST'])
@login_required
def add_object():
    form = forms.Object()
    if form.validate_on_submit():
        nfn = None
        if form.img.has_file():
            valid_files = ['jpg', 'png', 'gif', 'jpeg']
            pic = form.img.data
            h = hashlib.sha1(repr(time.time()).encode('utf-8')).hexdigest()
            ext = pic.filename.rsplit('.', 1)[1]
            if ext.lower() not in valid_files:
                flash('Verkeerde bestands type', 'error')
                return redirect(url_for('admin_panel.admin'))
            nfn = '{}.{}'.format(h, ext)
            pic.save(os.path.join(
                app.instance_path, 'uploads', nfn
            ))
        print(form.date_from.data)
        print(form.date_to.data)
        if not (form.date_from and form.date_to) and\
           not form.always.data:
            flash('Geen periode geselecteerd', 'error')
            return redirect(url_for('admin_panel.admin'))
        island = Island.query.filter(Island.name == form.island.data).first()
        cat = form.category.data

        dateFrom = None
        dateTo = None
        if not form.always.data:
            dateFrom = datetime.datetime.strptime(form.date_from.data, '%d-%m-%Y')
            dateTo = datetime.datetime.strptime(form.date_to.data, '%d-%m-%Y')

        o = Object(
                form.name.data,
                form.desc.data,
                nfn,
                dateFrom,
                dateTo,
                cat,
                island,
                always=form.always.data,
        )
        db.session.add(o)
        db.session.commit()
        flash('Object {} toegevoegd.'.format(form.name.data))
    return redirect(url_for('admin_panel.admin'))


@admin_panel.route('/modify_object', methods=['GET', 'POST'])
@login_required
def modify_object():
    form = forms.Modify_Object()
    if form.validate_on_submit():
        obj = form.name.data
        cur_obj = obj.name
        if form.remove.data:
            db.session.delete(obj)
            flash('{} is verwijderd.'.format(cur_obj))
        else:
            if form.img.has_file():  # New file uploaded for image
                valid_files = ['jpg', 'png', 'gif', 'jpeg']
                pic = form.img.data
                h = hashlib.sha1(repr(time.time()).encode('utf-8')).hexdigest()
                ext = pic.filename.rsplit('.', 1)[1]
                if ext.lower() not in valid_files:
                    flash('Verkeerde bestands type', 'error')
                    return redirect(url_for('admin_panel.admin'))
                nfn = '{}.{}'.format(h, ext)
                pic.save(os.path.join(
                    app.instance_path, 'uploads', nfn
                ))
                obj.img = nfn
            if form.new_name.data:
                obj.name = form.new_name.data
            if form.desc.data:
                obj.desc = form.desc.data
            if form.date_from.data:
                dateFrom = datetime.datetime.strptime(form.date_from.data, '%d-%m-%Y')
                obj.date_from = dateFrom
            if form.date_to.data:
                dateTo = datetime.datetime.strptime(form.date_to.data, '%d-%m-%Y')
                obj.date_to = dateTo
            if form.always.data:
                obj.always = form.always.data
            if form.category.data != obj.category.id:
                cat = form.category.data
                obj.category = cat
            if form.island.data != obj.island.name:
                isl = Island.query.\
                        filter(Island.name == form.island.data).first()
                obj.island = isl
            flash('{} is aangepast.'.format(cur_obj))
        db.session.commit()
    return redirect(url_for('admin_panel.admin'))


''' Category handlers '''


@admin_panel.route('/add_category', methods=['GET', 'POST'])
@login_required
def add_category():
    form = forms.Category()
    if form.validate_on_submit():
        cat = Category.query.filter(Category.name == form.name.data).first()
        if cat is None:
            cat = Category(form.name.data)

            if not form.img.has_file():
                flash('Icoon benodigd', 'error')
                return redirect(url_for('admin_panel.admin'))
            valid_files = ['jpg', 'png', 'gif', 'jpeg']
            pic = form.img.data
            h = hashlib.sha1(repr(time.time()).encode('utf-8')).hexdigest()
            ext = pic.filename.rsplit('.', 1)[1]
            if ext.lower() not in valid_files:
                flash('Verkeerde bestands type', 'error')
                return redirect(url_for('admin_panel.admin'))
            nfn = '{}.{}'.format(h, ext)
            pic.save(os.path.join(
                app.instance_path, 'uploads', nfn
            ))
            cat.img = nfn

            db.session.add(cat)
            db.session.commit()
            flash('Categorie {} toegevoegd.'.format(form.name.data))
        else:
            flash('Categorie {} bestaat al.'.format(form.name.data), 'error')
    return redirect(url_for('admin_panel.admin'))


@admin_panel.route('/modify_category', methods=['GET', 'POST'])
@login_required
def modify_category():
    form = forms.Modify_Category()
    if form.validate_on_submit():
        cat = form.category.data
        if cat is None:
            flash('Error..?', 'error')
            return redirect(url_for('admin_panel.admin'))
        cur_cat = cat.name
        if form.remove.data:
            if len(cat.objects) > 0:
                flash('{} kan niet worden verwijderd.\
                       Er zijn nog objecten in deze categorie'.format(cur_cat))
            else:
                db.session.delete(cat)
                flash('{} is verwijderd.'.format(cur_cat))
        else:
            if form.name.data:
                cat.name = form.name.data
            if form.img.has_file():
                valid_files = ['jpg', 'png', 'gif', 'jpeg']
                pic = form.img.data
                h = hashlib.sha1(repr(time.time()).encode('utf-8')).hexdigest()
                ext = pic.filename.rsplit('.', 1)[1]
                if ext.lower() not in valid_files:
                    flash('Verkeerde bestands type', 'error')
                    return redirect(url_for('admin_panel.admin'))
                nfn = '{}.{}'.format(h, ext)
                pic.save(os.path.join(
                    app.instance_path, 'uploads', nfn
                ))
                cat.img = nfn

            flash('{} is aangepast.'.format(cur_cat))
        db.session.commit()
    return redirect(url_for('admin_panel.admin'))


''' Island handlers '''


@admin_panel.route('/modify_island', methods=['GET', 'POST'])
@login_required
def modify_island():
    form = forms.Modify_Island()
    if form.validate_on_submit():
        isl = Island.query.filter(Island.name == form.island.data).first()
        if isl is None:
            flash('Error..?', 'error')
            return redirect(url_for('admin_panel.admin'))
        else:
            isl.desc = form.desc.data
            isl.car = form.car.data
            isl.airplane = form.airplane.data
            isl.color = form.color.data
            print(form.img.data)
            if form.img.has_file():  # New file uploaded for image
                valid_files = ['jpg', 'png', 'gif', 'jpeg']
                pic = form.img.data
                h = hashlib.sha1(repr(time.time()).encode('utf-8')).hexdigest()
                ext = pic.filename.rsplit('.', 1)[1]
                if ext.lower() not in valid_files:
                    flash('Verkeerde bestands type', 'error')
                    return redirect(url_for('admin_panel.admin'))
                nfn = '{}.{}'.format(h, ext)
                pic.save(os.path.join(
                    app.instance_path, 'uploads', nfn
                ))
                isl.img = nfn

            flash('{} is aangepast.'.format(isl.name))
            db.session.commit()
    return redirect(url_for('admin_panel.admin'))


''' User handlers '''


@admin_panel.route('/add_user', methods=['GET', 'POST'])
@login_required
def add_user():
    form = forms.Add_User()
    if form.validate_on_submit():
        usr = User.query.filter(User.username == form.username.data).first()
        if usr:
            flash('Gebruikersnaam is al in gebruik.')
            return redirect(url_for('admin_panel.admin'))
        hashed = bcrypt.hashpw(form.password.data.encode('UTF-8'),
                               bcrypt.gensalt())
        usr = User(form.username.data, hashed,
                   request.remote_addr)
        db.session.add(usr)

app/blueprints/admin_panel/templates/forms/add_category.html
    <div id="add_category">
        <h2>Nieuwe categorie toevoegen</h2>
        <form action="{{ url_for('admin_panel.add_category') }}" method="POST" name="add_category" enctype="multipart/form-data">
            {{ add_cat_form.csrf_token }}
            {{ macros.input(add_cat_form.name) }}
            <!-- {{ macros.input(add_cat_form.desc) }} -->
            {{ macros.input(add_cat_form.img) }}
            {{ add_cat_form.submit }}
        </form>
    </div>

app/blueprints/admin_panel/templates/forms/add_object.html
    <div id="add_object">
        <h2>Nieuw object toevoegen</h2>
        <form action="{{ url_for('admin_panel.add_object') }}" method="POST" name="add_object" enctype="multipart/form-data">
            {{ add_object_form.csrf_token }}
            {{ macros.input(add_object_form.name) }}
            {{ macros.input(add_object_form.desc) }}
            {{ macros.input(add_object_form.img) }}
            {{ macros.input(add_object_form.date_from) }}
            {{ macros.input(add_object_form.date_to) }}
            {{ macros.input(add_object_form.always) }}
            {{ macros.input(add_object_form.category) }}
            {{ macros.input(add_object_form.island) }}
            {{ add_object_form.submit }}
        </form>
    </div>

app/blueprints/admin_panel/templates/forms/add_user.html
    <div id="add_user">
        <h2>Nieuw gebruiker toevoegen</h2>
        <form action="{{ url_for('admin_panel.add_user') }}" method="POST" name="add_user">
            {{ add_object_form.csrf_token }}
            {{ macros.input(add_user_form.username) }}
            {{ macros.input(add_user_form.password) }}
            {{ add_user_form.submit }}
        </form>
    </div>

app/blueprints/admin_panel/templates/forms/modify_category.html
    <div id="modify_category">
        <h2>Bestaande categorie aanpassen</h2>
        <form action="{{ url_for('admin_panel.modify_category') }}" method="POST" name="modify_category" enctype="multipart/form-data">
            {{ mod_cat_form.csrf_token }}
            {{ macros.input(mod_cat_form.category) }}
            {{ macros.input(mod_cat_form.name) }}
            <!-- {{ macros.input(mod_cat_form.desc) }} -->
            {{ macros.input(mod_cat_form.img) }}
            {{ mod_cat_form.submit }}
            {{ mod_cat_form.remove }}
        </form>
    </div>

app/blueprints/admin_panel/templates/forms/modify_island.html
    <div id="modify_island">
        <h2>Eiland aanpassen</h2>
        <form action="{{ url_for('admin_panel.modify_island') }}" method="POST" name="modify_island" enctype="multipart/form-data">
            {{ mod_isl_form.csrf_token }}
            {{ macros.input(mod_isl_form.island) }}
            {{ macros.input(mod_isl_form.desc) }}
            {{ macros.input(mod_isl_form.img) }}
            {{ macros.input(mod_isl_form.car) }}
            {{ macros.input(mod_isl_form.airplane) }}
            {{ macros.input(mod_isl_form.color) }}
            {{ mod_isl_form.submit }}
        </form>
    </div>

app/blueprints/admin_panel/templates/forms/modify_object.html
    <div id="modify_object">
        <h2>Bestaand object aanpassen</h2>
        <form action="{{ url_for('admin_panel.modify_object') }}" method="POST" name="modify_object" enctype="multipart/form-data">
            {{ mod_object_form.csrf_token }}
            {{ macros.input(mod_object_form.name) }}
            {{ macros.input(mod_object_form.new_name) }}
            {{ macros.input(mod_object_form.desc) }}
            {{ macros.input_img(mod_object_form.img) }}
            {{ macros.input(mod_object_form.date_from) }}
            {{ macros.input(mod_object_form.date_to) }}
            {{ macros.input(mod_object_form.always) }}
            {{ macros.input(mod_object_form.category) }}
            {{ macros.input(mod_object_form.island) }}
            {{ mod_object_form.submit }}
            {{ mod_object_form.remove }}
        </form>
    </div>

app/blueprints/admin_panel/templates/forms/modify_user.html
    <div id="modify_user">
        <h2>Gebruiker aanpassen</h2>
        <form action="{{ url_for('admin_panel.modify_user') }}" method="POST" name="modify_user">
            {{ mod_object_form.csrf_token }}
            {{ macros.input(mod_user_form.user) }}
            {{ macros.input(mod_user_form.username) }}
            {{ macros.input(mod_user_form.password) }}
            {{ mod_user_form.submit }}
            {{ mod_user_form.remove }}
        </form>
    </div>